[tool.ruff]
fix = true
indent-width = 4
line-length = 120

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # pyflakes
    "F",
    # isort
    "I",
    # numpy
    "NPY",
    # flake8-bugbear
    "B"
]

[tool.ruff.lint.per-file-ignores]
"tests/test_rapids-check-pr-job-dependencies.py" = [
    # (pycodstyle) line too long
    "E501"
]
