#!/bin/bash
# A utility script that downloads an artifact archive from S3, untars it,
# and prints the location where it was untarred.
# The script can be used locally and in CI.
# Positional Arguments:
#   1) path to s3 artifact
#   2) http path to s3 artifact
#   3) location to untar it to
set -euo pipefail
source rapids-constants

s3_dl_path="$1"
http_dl_path="$2"
untar_dest="$3"

mkdir -p "${untar_dest}"

if [ "${CI:-false}" = "false" ]; then
  rapids-echo-stderr "Downloading and decompressing ${http_dl_path} into ${untar_dest}"
  wget -qO- "${http_dl_path}" | tar xzf - -C "${untar_dest}"
else
  rapids-echo-stderr "Downloading and decompressing ${s3_dl_path} into ${untar_dest}"
  aws s3 cp --only-show-errors "${s3_dl_path}" - | tar xzf - -C "${untar_dest}"
fi

# echo path to untarred contents
echo -n "${untar_dest}"
