#!/bin/bash
# Echo path to an artifact for a specific PR. Finds and uses the latest commit on the PR.
#
# Positional Arguments:
#   1) repo name
#   2) PR number
#   3) "cpp" or "python", to get the artifact for the C++ or Python build, respectively
#   4) "wheel" or "conda", to get the wheel or conda package artifact, respectively
#   5) [optional] commit hash, to get the artifact for a specific commit
#
# If fetching a wheel, RAPIDS_PY_WHEEL_NAME must be set to indicate the package
# name to fetch.
# Example Usage:
#   _rapids-get-pr-artifact rmm 1095 cpp
set -euo pipefail

repo="${1}"
pr="${2}"
package_type="${3}"
package_format="${4}"
commit="${5:-}"

if [[ "${package_format}" = "wheel" && -z "${RAPIDS_PY_WHEEL_NAME:+placeholder}" ]]; then
    echo "The RAPIDS_PY_WHEEL_NAME variable must be set when fetching a wheel artifact"
    exit 1
fi
artifact_name=$(RAPIDS_REPOSITORY="${repo}" rapids-package-name "${package_format}_${package_type}")

if [[ -z "${commit}" ]]; then
    commit=$(git ls-remote https://github.com/rapidsai/"${repo}".git refs/heads/pull-request/"${pr}" | cut -c1-7)
fi

rapids-get-artifact "ci/${repo}/pull-request/${pr}/${commit}/${artifact_name}"
