#!/bin/bash
# A utility script that downloads an artifact archive from Github Artifacts, unzips it,
# and prints the location where it was unzipped.
# The script can be used locally and in CI.
# Positional Arguments:
#   1) run_id of the Github Workflow run
#   2) name of the artifact to download
#   3) location to unzip it to
set -euo pipefail
source rapids-constants

github_run_id="$1"
pkg_name="$2"
unzip_dest="$3"

mkdir -p "${unzip_dest}"

rapids-echo-stderr "Downloading and decompressing ${pkg_name} from Run ID ${github_run_id} into ${unzip_dest}"
gh run download "${github_run_id}" --repo "${RAPIDS_REPOSITORY}" --name "${pkg_name}" --dir "${unzip_dest}" 

echo -n "${unzip_dest}"