#!/bin/bash
# _rapids-path
# A utility script to generate the URI path.

set -euo pipefail
source rapids-constants

repo_name="${RAPIDS_REPOSITORY##*/}"

s3_directory_id=""
s3_prefix=""

case "${RAPIDS_BUILD_TYPE}" in
  pull-request)
    # For PRs, we are using the 'trusted jobs on untrusted forks' paradigm
    # by copying PRs to branches named pull-request/$prnum
    # more info:
    #    CopyPRs plugin in ops-bot: https://github.com/rapidsai/ops-bot#plugins
    #    https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
    s3_directory_id="${RAPIDS_REF_NAME##*/}"
    s3_prefix="ci"
    ;;
  branch)
    s3_directory_id="${RAPIDS_REF_NAME}"
    s3_prefix="ci"
    ;;
  nightly)
    s3_directory_id="${RAPIDS_NIGHTLY_DATE}"
    s3_prefix="nightly"
    ;;
  *)
    rapids-echo-stderr "please pass a valid RAPIDS_BUILD_TYPE"
    exit 1
    ;;
esac

short_hash=${RAPIDS_SHA:0:7}

uri_path="${s3_prefix}/${repo_name}/"
if [[ "${RAPIDS_BUILD_TYPE}" != "nightly" ]]; then
  uri_path+="${RAPIDS_BUILD_TYPE}/"
fi
uri_path+="${s3_directory_id}/${short_hash}/"
