#!/bin/bash
#
# gpuci_conda_retry
#
# Compatibility wrapper that calls to the new rapids-conda-retry script

# Configurable env vars GPUCI_* are re-exported as RAPIDS_*

echo "'gpuci_conda_retry' is deprecated, please use 'rapids-conda-retry' instead" >&2

# alias old GPUCI_ env vars to new RAPIDS_ equivalents if they are set

if [[ -v GPUCI_CONDA_RETRY_MAX ]]; then
  export RAPIDS_CONDA_RETRY_MAX="${GPUCI_CONDA_RETRY_MAX}"
fi

if [[ -v GPUCI_CONDA_RETRY_SLEEP ]]; then
  export RAPIDS_CONDA_RETRY_SLEEP="${GPUCI_CONDA_RETRY_SLEEP}"
fi

rapids-conda-retry "$@"
