#!/bin/bash
#
# gpuci_retry
#
# Compatibility wrapper that calls to the new rapids-retry script

# Configurable env vars GPUCI_* are re-exported as RAPIDS_*

echo "'gpuci_retry' is deprecated, please use 'rapids-retry' instead" >&2

# alias old GPUCI_ env vars to new RAPIDS_ equivalents if they are set

if [[ -v GPUCI_RETRY_MAX ]]; then
  export RAPIDS_RETRY_MAX="${GPUCI_RETRY_MAX}"
fi

if [[ -v GPUCI_RETRY_SLEEP ]]; then
  export RAPIDS_RETRY_SLEEP="${GPUCI_RETRY_SLEEP}"
fi

rapids-retry "$@"
