#!/bin/bash
# A utility script that configures sccache for distributed compilation

case "$(uname -m)" in
    x86_64)
    CPU_ARCH=amd64
    ;;
    aarch64)
    CPU_ARCH=arm64
    ;;
    *)
    echo "Unsupported CPU architecture '$(uname -m)'" >&2
    exit 1
    ;;
esac

# Install sccache to /usr/bin
rapids-install-sccache

# Configure sccache client

# Set dynamically if unset
if ! test -n "${PARALLEL_LEVEL:+x}"; then
    # Memory (in KB) used by each `sccache <compiler> ...` invocation from ninja
    # * 1.5Mb for the shell launched by ninja
    # * 6MiB for each sccache client process
    # * round up
    mem_per_sccache_client="$((1024 * 8))"
    # It's usually around 400-600MiB, but be conservative
    # and assume the sccache daemon will use 1GiB of RAM
    mem_for_sccache_daemon="$((1 * 1024 * 1024))"
    # Preprocessor invocations take ~250Mb or so
    mem_for_preprocessor="$(($(nproc --all) * 250 * 1024))"
    # Available memory (in KB), for more details see free(1).
    mem_avail="$(cat /proc/meminfo | grep MemAvailable | tr -s '[:space:]' | cut -d' ' -f2)"
    # Total job count is available memory after accounting for `nproc` preprocessor calls
    # divided by the amount of memory required to invoke the sccache thin client process.
    export PARALLEL_LEVEL="$(((mem_avail - mem_for_preprocessor - mem_for_sccache_daemon) / mem_per_sccache_client))"
fi

export NVCC_APPEND_FLAGS="${NVCC_APPEND_FLAGS:+$NVCC_APPEND_FLAGS }-t=100"

# sccache configuration
export SCCACHE_ERROR_LOG="${SCCACHE_ERROR_LOG:-/tmp/sccache.log}"
export SCCACHE_SERVER_LOG="${SCCACHE_SERVER_LOG:-sccache=debug}"

# sccache-dist configuration
export SCCACHE_DIST_AUTH_TYPE="${SCCACHE_DIST_AUTH_TYPE:-token}"
export SCCACHE_DIST_MAX_RETRIES="${SCCACHE_DIST_MAX_RETRIES:-inf}"
export SCCACHE_DIST_REQUEST_TIMEOUT="${SCCACHE_DIST_REQUEST_TIMEOUT:-7140}"
export SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE="${SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE:-false}"
export SCCACHE_DIST_SCHEDULER_URL="https://${CPU_ARCH}.linux.sccache.rapids.nvidia.com"

# Disable build caching for release builds
if rapids-is-release-build; then
    export SCCACHE_NO_CACHE=1
fi

# Start the sccache client daemon
mkdir -p "$(dirname "$SCCACHE_ERROR_LOG")"
