#!/bin/bash
# Helper function that will exit with a non-zero code if the provided
# environment variable is not set.
# Note: Pass the environment variable's name as a string (e.g. "HOME"),
# not it's value (e.g. "$HOME").
# Usage:
#   rapids-require-env-var "RAPIDS_BUILD_TYPE"
set -e

ENV_VAR_NAME=$1

if [[ -z "${!ENV_VAR_NAME}" ]]; then
  ERR_STR="${ENV_VAR_NAME} is a required environment variable"

  if [[ -n "${RAPIDS_SCRIPT_NAME}" ]]; then
    ERR_STR+=" for [${RAPIDS_SCRIPT_NAME}]"
  fi

  echo "${ERR_STR}"
  exit 1
fi
