#!/bin/bash
# Downloads a wheel artifact archive from Github Artifacts, unzips it,
# and returns the path to the directory where it was unzipped.
#
# Positional Arguments:
#   1) a string of "cpp" or "python" which determines which wheel artifact
#      should be downloaded
set -eo pipefail
export RAPIDS_SCRIPT_NAME="rapids-download-wheels-from-github"

source rapids-prompt-local-repo-config

# Validate package type argument
pkg_type="$1"
case "${pkg_type}" in
  cpp|python)
    pkg_name="$(rapids-package-name "wheel_${pkg_type}")"
    ;;
  pure_python)
    pkg_name="$(rapids-package-name "wheel_python" --pure)"
    ;;
  *)
    rapids-echo-stderr 'Pass "cpp", "python", or "pure_python" as an argument.'
    exit 1
    ;;
esac

rapids-download-from-github "${pkg_name}"
