#!/bin/bash
# A utility script produces a date string

RAPIDS_DATE_STRING="$(date +%y%m%d)"
if [ "${GITHUB_ACTIONS:-false}" = "true" ]; then
  WORKFLOW_DATE=$(rapids-retry gh run view "${GITHUB_RUN_ID}" --json createdAt | jq -r '.createdAt')
  RAPIDS_DATE_STRING=$(date -d "${WORKFLOW_DATE}" +%y%m%d)
fi
export RAPIDS_DATE_STRING