#!/bin/bash
#
# rapids-logger
#
# provides a logging mechanism for scripts to report progress
#
function rapids-logger {
  TS=$(date '+%x %T')
  # shellcheck disable=SC2000
  MSG_CNT=$(echo "$@" | wc -c)
  WIDTH=$((MSG_CNT+6))
  BAR=""
  for ((i = 0 ; i <= WIDTH ; i++)); do
    BAR="${BAR}─"
  done

  echo -e "\n\033[32mRAPIDS logger\033[0m » [$TS]"
  echo -e "\033[32m┌${BAR}┐\033[0m"
  echo -e "\033[32m|    $*    |\033[0m"
  echo -e "\033[32m└${BAR}┘\033[0m\n"
}

rapids-logger "$@"
