#!/bin/bash
# A utility script that extracts all conda packages
# after being downloaded by rapids-download-conda-from-s3
set -eo pipefail
export RAPIDS_SCRIPT_NAME="rapids-extract-conda-files"

if [ -z "$1" ]; then
  rapids-echo-stderr "Must specify input argument: TARBALL_DIR"
  exit 1
fi

# dir that the extracted tarball are in
tarball_dir="$1"
{
  untar_dest=$(mktemp -d)
  mkdir -p "${untar_dest}"
  cd "${untar_dest}"
  find "${tarball_dir}" -name "*tar.bz2" -type f -print0 | xargs -0 -n 1 tar -v -xf
} >&2
echo -n "${untar_dest}"
