#!/bin/bash
#
# Checks if the current environment is authenticated to communicate with the GitHub API.
#
# If not, prompts for an interactive login to generate short-lived credentials.
#
# This exists primarily for interactive use cases, like trying to reproduce CI locally.
#

# In CI, assume that we've already authenticated by the time this script is called.
#
# 'gh auth status' makes network requests to the GitHub API. Skipping it in CI
# reduces the risk of hitting GitHub API rate limits.
#
if [ "${CI:-false}" = "true" ]; then
    rapids-echo-stderr "Detected CI=true. Skipping running 'gh auth status'."
elif ! gh auth status >&2; then
    rapids-echo-stderr "Not yet authenticated with GitHub."
    rapids-echo-stderr "Please authenticate with GitHub to continue."
    rapids-echo-stderr "To avoid these interactive prompts in the future, set environment variable 'GH_TOKEN' or run 'gh auth login' with the GitHub CLI."

    # Prompt for interactive login.
    #
    # By omitting --scopes, this will generate a short-lived GitHub auth token
    # with only the minimum required scopes.
    #
    # You can run 'gh auth status' afterwards to check the scopes the GitHub CLI granted.
    if ! gh auth login \
        --web \
        --git-protocol https \
        --hostname "github.com" \
        --skip-ssh-key >&2;
    then
        rapids-echo-stderr "GitHub authentication failed. Exiting.";
        # exit 1;
    fi
fi
