#!/bin/bash
#
# Initializes a `pip` constraint file. Ensures that environment variable
# `PIP_CONSTRAINT` is populated and points to a file that exists.
#
# This allows the unconditional use of that variable + script in CI scripts, like this:
#
#     source rapids-init-pip;
#     LIBRMM_WHEELHOUSE=$(
#       RAPIDS_PY_WHEEL_NAME="librmm_cu12" rapids-get-pr-artifact rmm 1909 cpp wheel
#     )
#     echo "librmm-${RAPIDS_PY_CUDA_SUFFIX} @ file://$(echo "${LIBRMM_WHEELHOUSE}"/librmm_*.whl)" >> "${PIP_CONSTRAINT}"
#
# This is intended to be `source`'d, not invoked as an executable.
#
# Note that the exact name `PIP_CONSTRAINT` is specifically recognized by `pip`:
# https://pip.pypa.io/en/latest/cli/pip_install/#cmdoption-c. Exporting it is important
# to ensure that the constraints are respected by all calls to `pip`, including nested
# calls that happen when setting up an isolation build environment for wheel builds.
#
PIP_CONSTRAINT="${PIP_CONSTRAINT:-$(mktemp -d)/constraints.txt}"
touch "${PIP_CONSTRAINT}"
export PIP_CONSTRAINT

# TODO: remove when https://github.com/rapidsai/ci-imgs/pull/357 is merged
#
# Patching out pypi.nvidia.com in this script allows a slow migration across RAPIDS
# without ever breaking CI (unlike just removing this in CI images and seeing what breaks).
if [[ "${RAPIDS_INIT_PIP_REMOVE_NVIDIA_INDEX:-}" == "true" ]]; then
    rapids-logger "patching pypi.nvidia.com out of pip.conf"
    sed -i '/pypi\.nvidia\.com/d' /etc/xdg/pip/pip.conf
    rapids-logger "updated 'pip.conf':"
    echo ""
    cat /etc/xdg/pip/pip.conf
    echo ""
fi
