#!/bin/bash
# Sets environment variables reused by other scripts here to interact with
# git, the GitHub API, and external artifact storage.
#
# If those variables are already defined when this script is called, it will not overwrite them.
# If not, it prompts interactively for them.
#
# Variables:
#
#   * RAPIDS_BUILD_TYPE   = One of "branch", "nightly", or "pull-request".
#   * RAPIDS_NIGHTLY_DATE = Date in YYYY-MM-DD format, used to organize nightly uploads.
#                           If not provided, the current system time is used.
#                           Only used when `RAPIDS_BUILD_TYPE` is "nightly".
#   * RAPIDS_REF_NAME     = Branch or tag (e.g. "main", "release/26.04", or "pull-request/1234")
#   * RAPIDS_REPOSITORY   = Repository the run happened in, in {org}/{repo} format (e.g. "rapidsai/rmm")
#   * RAPIDS_SHA          = Commit SHA on the repository indicated by `RAPIDS_REPOSITORY`.
#                           If not provided, this script assumes it's being run from within that repo
#                           and checks the commit pointed to by HEAD.
#

if [ "${CI:-false}" = "false" ]; then
  rapids-echo-stderr "Local run detected."

  if [ -z "${RAPIDS_BUILD_TYPE:-}" ]; then
    {
      echo ""
      read -r -p "Enter workflow type (one of: pull-request|branch|nightly): " RAPIDS_BUILD_TYPE
      export RAPIDS_BUILD_TYPE
      echo ""
      echo "Suppress this prompt in the future by setting the 'RAPIDS_BUILD_TYPE' environment variable:"
      echo "export RAPIDS_BUILD_TYPE=${RAPIDS_BUILD_TYPE}"
      echo ""
    } >&2
  fi

  if [ -z "${RAPIDS_REPOSITORY:-}" ]; then
    {
      echo ""
      read -r -p "Enter org/repository name (e.g. rapidsai/cudf): " RAPIDS_REPOSITORY
      export RAPIDS_REPOSITORY
      echo ""
      echo "Suppress this prompt in the future by setting the 'RAPIDS_REPOSITORY' environment variable:"
      echo "export RAPIDS_REPOSITORY=${RAPIDS_REPOSITORY}"
      echo ""
    } >&2
  fi

  if [ -z "${RAPIDS_REF_NAME:-}" ]; then
    {
      echo ""
      if [ "${RAPIDS_BUILD_TYPE}" = "pull-request" ]; then
        read -r -p "Enter pull-request number (e.g. 1546): " PR_NUMBER
        RAPIDS_REF_NAME=pull-request/${PR_NUMBER}
      else
        read -r -p "Enter branch name (e.g. main): " RAPIDS_REF_NAME
      fi
      export RAPIDS_REF_NAME
      echo ""
      echo "Suppress this prompt in the future by setting the 'RAPIDS_REF_NAME' environment variable:"
      echo "export RAPIDS_REF_NAME=${RAPIDS_REF_NAME}"
      echo ""
    } >&2
  fi

  if [ -z "${RAPIDS_SHA:-}" ]; then
    {
      echo ""
      if RAPIDS_SHA=$(set -e; git rev-parse HEAD 2> /dev/null); then
        echo "Using HEAD commit for artifact commit hash. Overwrite this by setting the 'RAPIDS_SHA' environment variable:"
        echo "export RAPIDS_SHA=${RAPIDS_SHA}"
      else
        echo "There was a problem acquiring the HEAD commit sha from the current directory."
        echo "Suppress this prompt in the future by ensuring the current directory is the '${RAPIDS_REPOSITORY}' git repository."
        read -r -p "Enter full commit sha (e.g. f15776cc449b0c8345f044f713c9c06eb13622f3): " RAPIDS_SHA
      fi
      echo ""
      export RAPIDS_SHA
    } >&2
  fi

  if [ "${RAPIDS_BUILD_TYPE}" = "nightly" ] && [ -z "${RAPIDS_NIGHTLY_DATE:-}" ]; then
    {
      echo ""
      read -r -p "Enter nightly date (e.g. 2023-06-20): " RAPIDS_NIGHTLY_DATE
      export RAPIDS_NIGHTLY_DATE
      echo ""
      echo "Suppress this prompt in the future by setting the 'RAPIDS_NIGHTLY_DATE' environment variable:"
      echo "export RAPIDS_NIGHTLY_DATE=${RAPIDS_NIGHTLY_DATE}"
      echo ""
    } >&2
  fi
fi
