#!/bin/bash

RAPIDS_CHANNEL="rapidsai-nightly"
DASK_CHANNEL="dask/label/dev"
NVIDIA_CHANNEL=""

# Replace dev/nightly channels if build is a release build
if rapids-is-release-build; then
  RAPIDS_CHANNEL="rapidsai"
  DASK_CHANNEL=""
fi

# Only include nvidia channel if we're on cuda11
IFS='.' read -ra CUDA_VERSION_ARRAY <<< "$RAPIDS_CUDA_VERSION"
if [ "${CUDA_VERSION_ARRAY[0]}" -eq "11" ]; then
  NVIDIA_CHANNEL="nvidia"
fi

channels=("$RAPIDS_CHANNEL" "$DASK_CHANNEL" "conda-forge" "$NVIDIA_CHANNEL")

_add_c_prefix() {
  for channel in "${channels[@]}"; do
    # Only echo out a channel if it is non-empty
    if [[ $channel ]]; then
      echo -n "--channel $channel "
    fi
  done
}

rapids-logger "Using channels: ${channels[*]}"

IFS=" " read -r -a RATTLER_CHANNELS <<< "$(_add_c_prefix)"
export RATTLER_CHANNELS

# Set default CLI args passed to `rattler-build`
RATTLER_ARGS=("--experimental" "--no-build-id" "--channel-priority" "disable" "--output-dir" "$RAPIDS_CONDA_BLD_OUTPUT_DIR")

rapids-logger "Using rattler-build args: ${RATTLER_ARGS[*]}"

export RATTLER_ARGS
