#!/bin/bash
# A utility script that generates CUDA suffix in the format "cu${VER}" where `$VER`
# is the CUDA version major. (For example, "cu11")
# Positional Arguments:
#   1) ctk-tag
set -eu -o pipefail

if [ -z "$1" ]; then
  rapids-echo-stderr "Must specify input argument: CTK_TAG"
  exit 1
fi

ctk_tag="$1"
ctk_major=$(echo "$ctk_tag" | cut -d'.' -f1)
cuda_suffix="cu${ctk_major}"

echo -n "${cuda_suffix}"
