#!/bin/bash
# Extracts all conda packages in a directory into another directory that only includes conda packages.
set -eo pipefail
export RAPIDS_SCRIPT_NAME="rapids-extract-conda-files"

if [ -z "${1:-}" ]; then
  rapids-echo-stderr "Must specify input argument: CONDA_PKG_DIR"
  exit 1
fi

# dir that the extracted conda packages are in
conda_pkg_dir="$1"
{
  conda_pkg_dest=$(mktemp -d)
  mkdir -p "${conda_pkg_dest}"
  cd "${conda_pkg_dest}"
  find "${conda_pkg_dir}" \( -name "*.tar.bz2" -o -name "*.conda" \) -type f -print0 | xargs -0 -n 1 cph extract --dest .
} >&2
echo -n "${conda_pkg_dest}"
