#!/bin/bash
# Checks whether a particular GitHub workflow job depends on all of the
# other jobs in the workflow.
#
# This is necessary since the RAPIDS branch protections are configured to require
# the "pr-builder" job to pass for all PRs. It's implied that that job depends
# on all other jobs in the workflow.
#
# An optional argument can be passed to ignore certain jobs from the check.
# The argument should be a space-separated list of job names, e.g.:
#  rapids-check-pr-job-dependencies "job1 job2 job3"
set -euo pipefail

export WORKFLOW_FILE=${WORKFLOW_FILE:-".github/workflows/pr.yaml"}
export PR_BUILDER_JOB_NAME=${PR_BUILDER_JOB_NAME:-"pr-builder"}
export IGNORED_JOBS=${1:-""}

WORKFLOW_JOBS=$(yq '((.jobs | keys) - [strenv(PR_BUILDER_JOB_NAME)])' "${WORKFLOW_FILE}")
export WORKFLOW_JOBS

PR_BUILDER_JOB_NEEDS=$(yq '(.jobs.[env(PR_BUILDER_JOB_NAME)].needs)' "${WORKFLOW_FILE}")
export PR_BUILDER_JOB_NEEDS

IGNORED_JOBS=$(yq -n 'strenv(IGNORED_JOBS) | trim | split(" ")')
export IGNORED_JOBS

MISSING_JOBS=$(yq -n '((env(WORKFLOW_JOBS) - env(PR_BUILDER_JOB_NEEDS)) - env(IGNORED_JOBS))')
export MISSING_JOBS

if yq -en 'env(MISSING_JOBS) | length != 0' >/dev/null 2>&1; then
  echo "'${PR_BUILDER_JOB_NAME}' job is missing the following dependent jobs:"
  yq -n 'env(MISSING_JOBS) | map("  - " + .) | join("\n")'

  echo ""
  echo "Update '${WORKFLOW_FILE}' to include these missing jobs for '${PR_BUILDER_JOB_NAME}'".
  echo "Alternatively, you may ignore these jobs by passing them as an argument to this script."
  exit 1
fi

if if_condition="$(yq -e '.jobs.[env(PR_BUILDER_JOB_NAME)].if' "${WORKFLOW_FILE}" 2>/dev/null)"; then
  if [[ "${if_condition}" != "always()" ]]; then
    echo "If '${PR_BUILDER_JOB_NAME}' job has an 'if' condition, it must be set to 'always()'."
    echo ""
    echo "Update '${WORKFLOW_FILE}' to set the correct 'if' condition."
    exit 1
  fi

  if yq -e '.jobs.[env(PR_BUILDER_JOB_NAME)].with.needs != "${{ toJSON(needs) }}"' "${WORKFLOW_FILE}" >/dev/null 2>&1; then
    echo "If '${PR_BUILDER_JOB_NAME}' job has an 'if' condition, it must also set the 'needs' input to '\${{ toJSON(needs) }}'."
    echo ""
    echo "Update '${WORKFLOW_FILE}' to add the following:"
    echo ""
    echo "with:"
    echo "  needs: \${{ toJSON(needs) }}"
    exit 1
  fi
fi

echo "${PR_BUILDER_JOB_NAME} depends on all other jobs."
