#!/bin/bash
# A utility script that tars up $RAPIDS_CONDA_BLD_OUTPUT_DIR and uploads it to S3
# Positional Arguments:
#   1) a string of "cpp" or "python" which determines which conda artifact
#      should be uploaded
set -eo pipefail

pkg_type="$1"
case "${pkg_type}" in
  cpp)
    ;&
  python)
    ;;
  *)
    echo 'Pass "cpp" or "python" as an argument.'
    exit 1
    ;;
esac

# Prepend `conda_` to PKG_TYPE
pkg_type="conda_$pkg_type"
pkg_name="$(rapids-package-name "$pkg_type")"

# Where conda build artifacts are output
rapids-require-env-var "RAPIDS_CONDA_BLD_OUTPUT_DIR"
path_to_tar_up="${RAPIDS_CONDA_BLD_OUTPUT_DIR}"

rapids-upload-to-s3 "${pkg_name}" "${path_to_tar_up}"
