#!/bin/bash
# A utility script that sets variables needed for `rattler-build`

# We only want the last two (of three) entries from splitting the `git describe` output on `-`
# so we purposefully overwrite `GIT_DESCRIBE_NUMBER` to avoid setting an unwanted variable

# shellcheck disable=SC2034
IFS=- read -r GIT_DESCRIBE_NUMBER GIT_DESCRIBE_NUMBER GIT_DESCRIBE_HASH <<< "$(git describe --tags)"
export GIT_DESCRIBE_NUMBER
export GIT_DESCRIBE_HASH
