#!/bin/bash
# A utility script that find all of the conda packages within a folder and
# uploads them to Anaconda.org
# Positional Arguments:
#   1) a directory path to search for conda packages
set -e

ECHO_PREFIX="    [rapids-upload-to-anaconda] "
SEARCH_DIR="$1"

if [ -z "${SEARCH_DIR}" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Please provide a search directory."
  exit 1
fi

if [ ! -v CONDA_TOKEN ] | [ -z "${CONDA_TOKEN}" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Env var CONDA_TOKEN must be set and not empty"
  exit 1
fi

if [ ! -d "${SEARCH_DIR}" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Directory ${SEARCH_DIR} does not exist."
  exit 1
fi

PKGS_TO_UPLOAD=$(find "${SEARCH_DIR}" -name "*.tar.bz2")
if [ -z "${PKGS_TO_UPLOAD}" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Couldn't find any packages to upload in: ${SEARCH_DIR}."
  ls -l "${SEARCH_DIR}/"*
  exit 1
fi

case "${BUILD_TYPE}" in
  branch)
    ;&
  nightly)
    ;;
  *)
    rapids-echo-stderr "${ECHO_PREFIX}Only branch builds and nightly builds are uploaded to Anaconda.org"
    exit 1
    ;;
esac

rapids-echo-stderr "${ECHO_PREFIX}Uploading packages to Anaconda.org: ${PKGS_TO_UPLOAD}"
# shellcheck disable=SC2086
anaconda \
  -t "${CONDA_TOKEN}" \
  upload \
  --label "${CONDA_UPLOAD_LABEL:-main}" \
  --skip-existing \
  --no-progress \
  ${PKGS_TO_UPLOAD}
