#!/bin/bash
# A utility script that examines environment variables provided
# by Jenkins to make some environment changes depending on whether
# a nightly or stable build is occurring.
set -e

# Remove nightly channels if build is a release build
if rapids-is-release-build; then
  conda config --system --remove channels rapidsai-nightly
  conda config --system --remove channels dask/label/dev
fi

# If nightly or branch build, append current YYMMDD to version
if ! rapids-is-release-build; then
  VERSION_SUFFIX=$(date +%y%m%d)
  export VERSION_SUFFIX
fi
