#!/bin/bash
# A utility script that downloads an artifact archive from S3, untars it,
# and prints the location where it was untarred.
# Positional Arguments:
#   1) package name to generate s3 path for
#   2) location to untar it to
set -euo pipefail
source rapids-constants
export RAPIDS_SCRIPT_NAME="rapids-download-from-s3"

if [ -z "$1" ] || [ -z "$2" ]; then
  rapids-echo-stderr "Must specify input arguments: PKG_NAME and UNTAR_DEST"
  exit 1
fi

s3_dl_path="$(rapids-s3-path)$1"

untar_dest="$2"
mkdir -p "${untar_dest}"

if [ "${CI:-false}" = "false" ]; then
  # shellcheck disable=SC2001
  s3_dl_path=$(echo "${s3_dl_path}" | sed "s|s3://${RAPIDS_DOWNLOADS_BUCKET}|https://${RAPIDS_DOWNLOADS_DOMAIN}|")
  rapids-echo-stderr "Downloading and decompressing ${s3_dl_path} into ${untar_dest}"
  wget -qO- "${s3_dl_path}" | tar xzf - -C "${untar_dest}"
else
  rapids-echo-stderr "Downloading and decompressing ${s3_dl_path} into ${untar_dest}"
  aws s3 cp --only-show-errors "${s3_dl_path}" - | tar xzf - -C "${untar_dest}"
fi


# echo path to untarred contents
echo -n "${untar_dest}"
