#!/bin/bash
# Compute a date string for use in package versions.

# TODO: remove 'RAPIDS_DATE_STRING' once all projects have been converted over to 'RAPIDS_DATETIME_STRING'

# for local builds, just compute right here
if [ "${CI:-false}" = "false" ]; then
  RAPIDS_DATE_STRING="$(date +%y%m%d)"
  RAPIDS_DATETIME_STRING="$(date -u +'%y%m%d%H%M%S')"
else
  WORKFLOW_DATE=$(rapids-retry gh run view "${GITHUB_RUN_ID}" --json createdAt | jq -r '.createdAt')
  RAPIDS_DATE_STRING=$(date -d "${WORKFLOW_DATE}" +%y%m%d)

  # In CI, 'RAPIDS_DATETIME_STRING' should already be set in the environment.
  RAPIDS_DATETIME_STRING="${RAPIDS_DATETIME_STRING:-}"
fi

export RAPIDS_DATE_STRING
export RAPIDS_DATETIME_STRING
