#!/bin/bash
# A utility script that downloads a conda artifact archive from Github Artifacts, unzips it,
# and returns the path to the directory where it was unzipped.
# Positional Arguments:
#   1) a string of "cpp" or "python" which determines which conda artifact
#      should be downloaded
set -euo pipefail
export RAPIDS_SCRIPT_NAME="rapids-download-conda-from-github"

pkg_type="$1"
# Validate package type argument
if [[ "${pkg_type}" != "cpp" && "${pkg_type}" != "python" ]]; then
  rapids-echo-stderr 'Pass "cpp" or "python" as an argument.'
  exit 1
fi

source rapids-prompt-local-repo-config

# Prepend `conda_` to PKG_TYPE for rapids-package-name function
pkg_type="conda_${pkg_type}"
pkg_name="$(rapids-package-name "$pkg_type")"

rapids-download-from-github "${pkg_name}"
