#!/bin/bash
# A utility script produces a date string

# TODO: remove default value after calling scripts are updated
FORMAT_ARG="${1:-second}"

case "${FORMAT_ARG}" in
  day)
    FORMAT="%y%m%d"
    ;;
  second)
    FORMAT="%s"
    ;;
  *)
    rapids-echo-stderr "Invalid format argument: ${FORMAT_ARG}"
    exit 1
    ;;
esac

RAPIDS_DATE_STRING="$(date +${FORMAT})"
if [ "${GITHUB_ACTIONS:-false}" = "true" ]; then
  WORKFLOW_DATE=$(rapids-retry gh run view "${GITHUB_RUN_ID}" --json createdAt | jq -r '.createdAt')
  RAPIDS_DATE_STRING=$(date -d "${WORKFLOW_DATE}" +${FORMAT})
fi
export RAPIDS_DATE_STRING
