#!/bin/bash
# A utility script that configures conda channels

conda_channel_in_config() {
  channel_id=${1:?err}
  conda config --json --get channels \
  | jq -r --arg c "${channel_id}" '."get"."channels" | any(. == $c )'
}

# Only try to run 'conda config --remove' if the channel exists in the config.
# This is here to avoid errors if this script is invoked multiple times in the same environment.
remove_conda_channel() {
  channel_id=${1:?err}
  in_config=$(conda_channel_in_config "${channel_id}")
  if [[ "${in_config}" == "true" ]]; then
    conda config --system --remove channels "${channel_id}"
  else
    echo "[rapids-configure-conda-channels] channel '${channel_id}' not found via 'conda config --get channels'"
  fi
}

# Remove nightly channels if build is a release build
if rapids-is-release-build; then
  remove_conda_channel 'rapidsai-nightly'
  remove_conda_channel 'dask/label/dev'
else
  # exclude stable channel from all non-release builds.
  remove_conda_channel 'rapidsai'
fi
