#!/bin/bash
# A utility script that tars up a wheel directory and uploads it to S3
# Positional Arguments:
#   1) wheel path to tar up
set -e

pkg_type="$1"
if [ "${pkg_type}" != "cpp" ] && [ "${pkg_type}" != "python" ]; then
    rapids-echo-error "Wheel cpp packages are now supported."
    rapids-echo-error "You must specify package type as the first argument to rapids-upload-wheels-to-s3"
fi

# remove pkg_type from args because we handle it in this script
shift;

if [ "${CI:-false}" = "false" ]; then
  rapids-echo-stderr "Packages from local builds cannot be uploaded to S3."
  rapids-echo-stderr "Open a PR to have successful builds uploaded."
  exit 0
fi

pkg_name="$(rapids-package-name "wheel_${pkg_type}")"

rapids-upload-to-s3 "${pkg_name}" "$@"
