#!/bin/bash
#
# rapids-print-env
#
# Prints summary of environment

rapids-logger "Print env"
env | sort

rapids-logger "Print system info"
uname -a

rapids-logger "Check python version"
python --version

if command -v conda > /dev/null; then
  rapids-logger "Check conda environment"
  conda info
  conda config --show-sources
  conda list --show-channel-urls
fi
