#!/bin/bash
# Downloads a conda artifact archive from Github Artifacts, unzips it,
# and returns the path to the directory where it was unzipped.
# Positional Arguments:
#   1) a string of "cpp" or "python" which determines which conda artifact
#      should be downloaded
set -euo pipefail
export RAPIDS_SCRIPT_NAME="rapids-download-conda-from-github"

source rapids-prompt-local-repo-config

# Validate package type argument
pkg_type="$1"
case "${pkg_type}" in
  cpp|python)
    pkg_name="$(rapids-package-name "conda_${pkg_type}")"
    ;;
  *)
    rapids-echo-stderr 'Pass "cpp" or "python" as an argument.'
    exit 1
    ;;
esac

rapids-download-from-github "${pkg_name}"
