#!/bin/bash
# A utility script that downloads an artifact archive from S3, untars it,
# and prints the location where it was untarred.
# Positional Arguments:
#   1) package name to generate s3 path for
#   2) location to untar it to
set -eou pipefail

ECHO_PREFIX="    [rapids-download-from-s3] "

repo_name="${GITHUB_REPOSITORY##*/}"

if [ -z "$1" ] || [ -z "$2" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Must specify input arguments: PKG_NAME and UNTAR_DEST"
  exit 1
fi

pkg_name="$1"
s3_dl_path=$(rapids-s3-path $pkg_name)

untar_dest="$2"
mkdir -p "${untar_dest}"

rapids-echo-stderr "${ECHO_PREFIX}Downloading and decompressing ${s3_dl_path} into ${untar_dest}"
aws s3 cp --only-show-errors "${s3_dl_path}" - | tar xzf - -C "${untar_dest}"

# echo path to untarred contents
echo -n "${untar_dest}"
