#!/bin/bash
# A utility script that tars up an arbitrary directory or file and uploads it to S3
# Positional Arguments:
#   1) the path to the directory or file to tar up
#   2) the name of the artifact (final will be `${repo_name}_${artifact_name}.tar.gz`)
set -eo pipefail

if [ -z "$1" ] || [ -z "$2" ]; then
  echo_stderr "Must specify both input arguments: FILE_TO_UPLOAD and ARTIFACT_NAME"
  exit 1
fi

rapids-upload-to-s3 "$1" "$2"
