#!/bin/bash
# A utility script that downloads a docker image from S3
# Positional Arguments:
#   1) image tag
set -eo pipefail
source rapids-constants
export RAPIDS_SCRIPT_NAME="rapids-download-docker-from-s3"

tmp_dir="$(mktemp -d)"

if [ -z "$1" ]; then
  rapids-echo-stderr "Must specify input argument: IMAGE_TAG"
  exit 1
fi

docker_image="$1"

# replace "rapidsai/..." with "rapidsai_..." to use as file name
docker_image_no_slash="$(echo ${docker_image} | sed 's#/#_#g')"
docker_image_s3_name="docker_${docker_image_no_slash}.tar.gz"
tmp_fname="${tmp_dir}/${docker_image_no_slash}.tar.gz"

# download .tar.gz into tmpdir
s3_dl_path="$(rapids-s3-path)${docker_image_s3_name}"
aws s3 cp --only-show-errors "${s3_dl_path}" "${tmp_fname}"

# load into docker
docker load < "${tmp_fname}"
