#!/bin/bash
# A utility script that examines environment variables provided
# by Jenkins to make some environment changes depending on whether
# a nightly or stable build is occurring.
set -euo pipefail

rapids-configure-conda-channels

source rapids-configure-sccache

source rapids-date-string-conda
