#!/bin/bash
# Gets RAPIDS version from a git tag.
# If `git describe` returns "v23.02.00a", then the
# `sed` command will remove the alpha characters and
# the `cut` command will return the first two fields,
# resulting in "23.02".
set -euo pipefail


git describe --abbrev=0 --tags | sed 's/[a-zA-Z]//g' | cut -d '.' -f -2
