#!/bin/bash
# Echo path to an artifact for a specific PR. Finds and uses the latest commit on the PR.
#
# Positional Arguments:
#   1) repo name
#   2) PR number
#   3) "cpp" or "python", to get the artifact for the C++ or Python build, respectively
#   4) [optional] commit hash, to get the artifact for a specific commit
#
# Example Usage:
#   rapids-get-pr-conda-artifact rmm 1095 cpp

set -euo pipefail

repo="$1"
pr="$2"

if [[ $# -eq 4 ]]
then
    commit="$4"
else
    commit=$(git ls-remote https://github.com/rapidsai/"${repo}".git refs/heads/pull-request/"${pr}" | cut -c1-7)
fi

rapids_cuda_major="${RAPIDS_CUDA_VERSION%%.*}"
python_majorminor=$(python --version | sed -E 's/Python ([0-9]+)\.([0-9]+)\.[0-9]+/\1\2/g')

if [[ $3 == "cpp" ]]
then
    rapids-get-artifact ci/"${repo}"/pull-request/"${pr}"/"${commit}"/"${repo}"_conda_cpp_cuda"${rapids_cuda_major}"_"$(arch)".tar.gz
elif [[ $3 == "python" ]]
    rapids-get-artifact ci/"${repo}"/pull-request/"${pr}"/"${commit}"/"${repo}"_conda_python_cuda"${rapids_cuda_major}"_"${python_majorminor}"_"$(arch)".tar.gz
else
    echo "Error: 3rd argument must be 'cpp' or 'python'"
    exit 1
fi
