#!/bin/bash
# A utility script that examines environment variables provided
# by Jenkins to make some environment changes depending on whether
# a nightly or stable build is occurring.
set -euo pipefail

# Remove nightly channels if build is a release build
if rapids-is-release-build; then
  conda config --system --remove channels rapidsai-nightly
  conda config --system --remove channels dask/label/dev
fi

if [ "${CI:-false}" = "false" ]; then
  # Configure sccache for read-only mode since no credentials
  # are available in local builds.
  export SCCACHE_S3_NO_CREDENTIALS=true
  export PARALLEL_LEVEL=${PARALLEL_LEVEL:-$(nproc)}
  export RAPIDS_BUILD_TYPE=${RAPIDS_BUILD_TYPE:-"pull-request"}
fi

RAPIDS_DATE_STRING="$(date +%y%m%d)"
if [ "${GITHUB_ACTIONS:-false}" = "true" ]; then
  WORKFLOW_DATE=$(rapids-retry gh run view "${GITHUB_RUN_ID}" --json createdAt | jq -r '.createdAt')
  RAPIDS_DATE_STRING=$(date -d "${WORKFLOW_DATE}" +%y%m%d)
fi
export RAPIDS_DATE_STRING
