#!/bin/bash
# Downloads an artifact, extracts it to a directory, and
# echoes the resulting directory's path
# Positional Arguments:
#   1) path to an artifact (e.g. ci/cudf/pull-request/12602/aa4da21/cudf_conda_python_cuda11_38_x86_64.tar.gz)
# Example Usage:
#   rapids-get-artifact ci/cudf/pull-request/12602/aa4da21/cudf_conda_python_cuda11_38_x86_64.tar.gz
set -euo pipefail
source rapids-constants

s3_dl_path="s3://${RAPIDS_DOWNLOADS_BUCKET}/${1}"
untar_dest=$(mktemp -d)

_rapids-download-from-s3 "$s3_dl_path" "$untar_dest"
