#!/bin/bash
# A utility script that tars up a specified directory and uploads it to S3
# Positional Arguments:
#   1) package name
#   2) path to tar up
set -eou pipefail

ECHO_PREFIX="    [rapids-upload-to-s3] "

if [ -z "$1" ] || [ -z "$2" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Must specify both input arguments: PACKAGE_NAME and PATH_TO_TAR_UP"
  exit 1
fi

package_name="$1"
path_to_tar_up="$2"

s3_dest_path="$(rapids-s3-path ${package_name})"

if [ -d "${path_to_tar_up}" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Path to upload is a directory, creating .tar.gz"

  # Tar.gz to stdout and pipe that to the s3 command, no need for a local file
  tar czfv - -C "${path_to_tar_up}" . | aws s3 cp --only-show-errors - "${s3_dest_path}"
  
  browsable_url="$(dirname ${s3_dest_path})/"
elif [ -f "${path_to_tar_up}" ]; then
  rapids-echo-stderr "${ECHO_PREFIX}Path to upload is a file, uploading it directly"

  aws s3 cp --only-show-errors "${path_to_tar_up}" "${s3_dest_path}"
  browsable_url="${s3_dest_path}"
fi

rapids-echo-stderr "${ECHO_PREFIX}Browse uploads: ${browsable_url/s3:\/\/rapids-downloads\//https:\/\/downloads.rapids.ai\/}"
