#!/bin/bash
# Downloads and decompresses a wheel artifact for a specific PR from GitHub Artifacts.
# Finds and uses the latest commit on the PR.
#
# Positional Arguments:
#   1) repo name
#   2) PR number
#   3) "cpp" or "python", to get the wheel artifact for the C++ or Python build, respectively
#   4) [optional] commit hash, to get the wheel artifact for a specific commit
#
# Optional Environment Variables:
#   RAPIDS_UNZIP_DIR: directory to unzip the wheel artifact into
#
# Example Usage:
#   rapids-get-pr-wheel-artifact-github rmm 1095 cpp
set -euo pipefail
export RAPIDS_SCRIPT_NAME="rapids-get-pr-wheel-artifact-github"

_rapids-get-pr-artifact "${1}" "${2}" "${3}" wheel "${4:-}"
