#!/bin/bash
# A utility script that downloads wheel artifacts from Github Artifacts to a temporary directory and returns the path to the directory
set -eo pipefail

source rapids-prompt-local-repo-config

pkg_type="$1"
if [ "${pkg_type}" = "cpp" ] || [ "${pkg_type}" = "python" ]; then
    # remove pkg_type from args because we handle it in this script
    shift;
    pkg_name="$(rapids-package-name "wheel_${pkg_type}")"
fi

rapids-download-from-github "${pkg_name}"
