#!/bin/bash
# Downloads and decompresses a conda artifact for a specific PR from GitHub Actions artifact store.
# Finds and uses the latest commit on the PR.
#
# Echoes an absolute path to the directory the files were downloaded to.
#
# Positional Arguments:
#   1) repo name
#   2) PR number
#   3) "cpp" or "python", to get the artifact for the C++ or Python build, respectively
#   4) [optional] commit hash, to get the artifact for a specific commit
#
# Example Usage:
#
#   RMM_CHANNEL=$(rapids-get-pr-conda-artifact rmm 1095 python)
#   conda install --channel "${RMM_CHANNEL}" rmm
#
set -euo pipefail

_rapids-get-pr-artifact "${1}" "${2}" "${3}" conda "${4:-}"
