#!/bin/bash
#
# rapids-print-env
#
# Prints summary of environment

rapids-logger "Print env"
env | sort

rapids-logger "Print arch"
arch

rapids-logger "Check python version"
python --version

rapids-logger "Check conda environment"
conda info
conda config --show-sources
conda list --show-channel-urls
