#!/bin/bash
# A utility script that uploads a docker image tag to S3
# Positional Arguments:
#   1) image tag
set -eo pipefail
export RAPIDS_SCRIPT_NAME="rapids-upload-docker-to-s3"

tmp_dir="$(mktemp -d)"

if [ -z "$1" ]; then
  rapids-echo-stderr "Must specify input argument: IMAGE_TAG"
  exit 1
fi

docker_image="$1"

# replace "/..." with "_..." to use as file name
docker_image_no_slash="${docker_image//\//_}"
docker_image_s3_name="docker_${docker_image_no_slash}.tar.gz"
tmp_fname="${tmp_dir}/${docker_image_no_slash}.tar.gz"

docker save "${docker_image}" | gzip > "${tmp_fname}"

rapids-upload-to-s3 "${docker_image_s3_name}" "${tmp_fname}"
