#!/bin/bash
# A utility script that downloads a conda artifact archive from S3, untars it,
# and prints the location where it was untarred.
# Positional Arguments:
#   1) a string of "cpp" or "python" which determines which conda artifact
#      should be downloaded
set -euo pipefail
export RAPIDS_SCRIPT_NAME="rapids-download-conda-from-s3"

pkg_type="$1"
case "${pkg_type}" in
  cpp)
    ;&
  python)
    ;;
  *)
    rapids-echo-stderr 'Pass "cpp" or "python" as an argument.'
    exit 1
    ;;
esac

rapids-prompt-local-repo-config

# Prepare empty dir to extract tarball to
channel="/tmp/${pkg_type}_channel"

# Prepend `conda_` to PKG_TYPE for rapids-package-name function
pkg_type="conda_${pkg_type}"
pkg_name="$(rapids-package-name "$pkg_type")"

rapids-download-from-s3 "${pkg_name}" "${channel}"
