#!/bin/bash
# A utility script that installs sccache
set -euo pipefail

SCCACHE_VERSION="${SCCACHE_VERSION:-"latest"}"
SCCACHE_REPO="${SCCACHE_REPO:-"rapidsai/sccache"}"

SCCACHE_BIN_DIR="$(dirname "$(which sccache 2>/dev/null || echo "/usr/bin/sccache")")"
CURRENT_SCCACHE_VERSION="$(command -v sccache &>/dev/null && sccache --version | cut -d' ' -f2 || echo "sccache not installed")"

if test "$SCCACHE_VERSION" = rapids; then
    SCCACHE_VERSION="latest"
    SCCACHE_REPO="rapidsai/sccache"
fi

rapids-prompt-local-github-auth

if [ "${SCCACHE_VERSION:-latest}" = latest ]; then
    SCCACHE_VERSION="$(rapids-retry --quiet gh release view --repo "${SCCACHE_REPO}" --json tagName --jq '.tagName | sub("^v"; "")')"
fi

if [ -n "${CURRENT_SCCACHE_VERSION##"${SCCACHE_VERSION}"}" ]; then
    echo "Downloading sccache v${SCCACHE_VERSION}..." >&2
    SCCACHE_ASSET="sccache-v${SCCACHE_VERSION}-$(uname -m)-unknown-linux-musl.tar.gz"
    rapids-retry gh release download "v${SCCACHE_VERSION}" --repo "${SCCACHE_REPO}" --pattern "${SCCACHE_ASSET}" --output - \
        | tar -C "$SCCACHE_BIN_DIR" -zf - --overwrite --wildcards --strip-components=1 -x '*/sccache'
    echo "Installed $(sccache --version) to $(which sccache)" >&2
else
    echo "sccache v${SCCACHE_VERSION} is already installed, skipping" >&2
fi
