#!/bin/bash
# Prints the RAPIDS version major/minor based on the VERSION file. Its output is meant to be stored in a variable.
# Assumed to be run from the repository root.
# See also: rapids-version
#
# $ rapids-version-major-minor
# 24.00
set -euo pipefail

readonly regex="^([0-9]{2})\.([0-9]{2})\.([0-9]{2}).*$"

[[ -f VERSION ]]
grep -E -q "$regex" VERSION
sed -E -e "s/$regex/\1.\2/" VERSION
