#!/bin/bash
#
# rapids-print-env
#
# prints summary of environment
#

rapids-logger "Get env"
env | sort

rapids-logger "Check python version"
python --version

rapids-logger "Check conda environment"
conda info
conda config --show-sources
conda list --show-channel-urls
