#!/bin/bash
# A utility script that examines environment variables provided by
# GitHub Actions to determine whether the current build is a "release" build.
# A "release" build occurs when the GITHUB_REF environment variable matches
# the pattern "refs/tags/vYY.MM.PP".
# Example:
#    if rapids-is-release-build; then echo "hi"; fi
set -e
export RAPIDS_SCRIPT_NAME="rapids-is-release-build"

if [[ "${GITHUB_REF}" =~ ^refs/tags/v[0-9]{1,2}.[0-9]{2}.[0-9]{2}$ ]]; then
  rapids-echo-stderr "is release build"
  exit 0
fi
rapids-echo-stderr "is not release build"
exit 1
