#!/bin/bash
# Echo path to an artifact for a specific PR. Finds and uses the latest commit on the PR.
#
# Positional Arguments:
#   1) repo name
#   2) PR number
#   3) "cpp" or "python", to get the artifact for the C++ or Python build, respectively
#   4) [optional] commit hash, to get the artifact for a specific commit
#
# Example Usage:
#   rapids-get-pr-conda-artifact rmm 1095 cpp
set -euo pipefail

rapids-get-pr-artifact "${1}" "${2}" "${3}" conda "${4:-}"
