#!/bin/bash
# Wraps arbitrary commands with arbitrary args. Emits an OpenTelemetry span for tracing the command
#
set -x

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

RAPIDS_OTEL_TRACES_EXPORTER="${RAPIDS_OTEL_TRACES_EXPORTER:-${RAPIDS_OTEL_EXPORTER:-"console"}}"
RAPIDS_OTEL_METRICS_EXPORTER="${RAPIDS_OTEL_METRICS_EXPORTER:-${RAPIDS_OTEL_EXPORTER:-"console"}}"
RAPIDS_OTEL_LOGS_EXPORTER="${RAPIDS_OTEL_LOGS_EXPORTER:-${RAPIDS_OTEL_EXPORTER:-"console"}}"
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces}"
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT="${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:-${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics}"
OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:-${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs}"
export TRACEPARENT
export OTEL_SERVICE_NAME

if [[ $(type otel-cli >/dev/null 2>&1) -eq 0 ]] && [ "$TRACEPARENT" != "" ]; then
    echo "Running command with OpenTelemetry instrumentation" >&2;

    if [ "$OTEL_SERVICE_NAME" = "" ]; then
        echo "WARNING: OTEL_SERVICE_NAME variable not provided. Traces from different steps may not be associated correctly. >&2"
    fi

    # Some commands have instrumentation. For example, conda-build has monkey-patched instrumentation
    # that can be activated with the opentelemetry-instrument command. For these commands,
    # we replace the command with the wrapped command, quoted as a whole for the purposes
    # of otel-cli exec, so that flags don't get confused.
    case "$1" in
        conda* )
        echo "using opentelemetry-instrument for command" >&2;
        echo "TRACEPARENT prior to otel-cli exec is: \"${TRACEPARENT}\"" >&2;
        STEP_TRACEPARENT=$("${SCRIPT_DIR}/rapids-get-telemetry-traceparent" "${OTEL_SERVICE_NAME}" "${STEP_NAME}")

        # otel-cli creates a span for us that bridges the traceparent from the parent process
        # into the command we're wrapping
        #     --service "${OTEL_SERVICE_NAME}" \
        # shellcheck disable=SC2086,SC2048
        otel-cli exec \
            --name "Run instrumented \"$*\"" \
            --force-parent-span-id "$(cut -d'-' -f3 <<<"$STEP_TRACEPARENT")" \
            --verbose \
            -- \
                opentelemetry-instrument \
                "$@"
        ;;
        * )
        # shellcheck disable=SC2086,SC2048
        otel-cli exec \
            --name "Run instrumented \"$*\"" \
            --force-parent-span-id "$(cut -d'-' -f3 <<<"$STEP_TRACEPARENT")" \
            --verbose \
            -- "$@"
        ;;
    esac
        RETURN_STATUS=$?
else
    "$@"
    RETURN_STATUS=$?
fi

exit "${RETURN_STATUS}"
